receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  azuremonitor:
    instrumentation_key: "6fe2b979-287d-4fdf-8f3d-3200f731320e"
  logging: # Optional: Logs telemetry output for debugging
  otlp:
    endpoint: "http://localhost:4317"
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [azuremonitor, logging]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [azuremonitor, logging]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [azuremonitor, logging]
