// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WeatherForecast.Infrastructure.Models;

public partial class WeatherForecastDbContext : DbContext
{
    public WeatherForecastDbContext()
    {
    }

    public WeatherForecastDbContext(DbContextOptions<WeatherForecastDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Weather> Weather { get; set; }



    public virtual DbSet<Location> Location { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Weather>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CurrentW__3214EC071ACD61C2");

            entity.Property(e => e.Time).HasMaxLength(50);

            entity.HasOne(d => d.Location).WithMany(p => p.Weather)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK__CurrentWe__Weath__4BAC3F29");
        });
               

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WeatherR__3214EC07EB3E0199");

            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Department).HasMaxLength(100);
            entity.Property(e => e.Timezone).HasMaxLength(50);
            entity.Property(e => e.TimezoneAbbreviation).HasMaxLength(10);
            
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}