// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeatherForecast.Infrastructure.Models;

public partial class Weather
{
    public int Id { get; set; }

    public int? LocationId { get; set; }

    public string Time { get; set; }

    public int? Interval { get; set; }

    public double? Temperature { get; set; }

    public double? Windspeed { get; set; }

    public int? Winddirection { get; set; }

    public int? IsDay { get; set; }

    public int? Weathercode { get; set; }

    public virtual Location Location { get; set; }
}