id: /subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/honeycomb-collectordatasync/providers/Microsoft.App/containerapps/collector
identity:
  type: None
location: UK South
name: collector
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: collector.blueground-9681b7a3.uksouth.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 4318
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: null
    registries: null
    secrets: null
    service: null
  customDomainVerificationId: A7B00043658BFE1EB45E4C8CC19B21892555A876738A411BCE9C62ED55822C38
  delegatedIdentities: []
  environmentId: /subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/honeycomb-collectordatasync/providers/Microsoft.App/managedEnvironments/collector-envdatasync
  eventStreamEndpoint: https://uksouth.azurecontainerapps.dev/subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/honeycomb-collectordatasync/containerApps/collector/eventstream
  latestReadyRevisionName: collector--mrdojtf
  latestRevisionFqdn: collector--mrdojtf.blueground-9681b7a3.uksouth.azurecontainerapps.io
  latestRevisionName: collector--mrdojtf
  managedEnvironmentId: /subscriptions/023b2039-5c23-44b8-844e-c002f8ed431d/resourceGroups/honeycomb-collectordatasync/providers/Microsoft.App/managedEnvironments/collector-envdatasync
  outboundIpAddresses:
  - 20.108.216.9
  - 20.108.217.125
  - 74.177.201.70
  - 131.145.91.209
  - 4.158.91.74
  - 4.158.89.64
  - 131.145.40.6
  - 74.177.198.189
  - 85.210.223.160
  - 74.177.245.93
  - 74.177.198.181
  - 131.145.77.209
  - 20.108.124.221
  - 74.177.162.123
  - 20.26.109.122
  - 131.145.124.57
  - 85.210.222.64
  - 20.26.109.180
  - 74.177.141.127
  - 85.210.223.56
  - 74.177.245.142
  - 131.145.83.126
  - 131.145.99.107
  - 20.108.125.221
  - 4.159.25.18
  - 4.158.92.46
  - 20.162.145.125
  - 4.158.143.149
  - 4.158.143.92
  - 4.250.234.44
  - 20.90.238.99
  - 20.90.239.180
  - 85.210.163.187
  - 74.177.240.109
  - 172.166.80.179
  - 131.145.9.241
  - 85.210.166.17
  - 85.210.48.136
  - 74.177.120.102
  - 131.145.48.93
  - 85.210.163.208
  - 74.177.193.62
  - 20.108.130.227
  - 20.108.130.191
  - 85.210.25.6
  - 85.210.24.221
  - 4.158.34.249
  - 20.162.138.167
  - 4.158.113.223
  - 4.159.3.89
  - 85.210.170.18
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: CONTAINER_APP_NAME
        value: collector
      - name: CONTAINER_APP_REVISION
        value: rev1
      image: otel/opentelemetry-collector-contrib
      name: collector
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: Consumption
resourceGroup: honeycomb-collectordatasync
systemData:
  createdAt: '2025-07-05T15:06:17.1682176'
  createdBy: leyegora@yahoo.fr
  createdByType: User
  lastModifiedAt: '2025-07-05T15:49:30.0920249'
  lastModifiedBy: leyegora@yahoo.fr
  lastModifiedByType: User
type: Microsoft.App/containerApps
