services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411


  jaeger:
    image: jaegertracing/all-in-one:1.56.0
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      # - 4317:4317
      - 4318:4318


    environment:
      COLLECTOR_OTLP_ENABLED: true