// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeatherForecast.Infrastructure.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Department { get; set; }

    public int? DepartmentCode { get; set; }

    public string City { get; set; }

    public int? PostalCode { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public double? GenerationTimeMs { get; set; }

    public int? UtcOffsetSeconds { get; set; }

    public string Timezone { get; set; }

    public string TimezoneAbbreviation { get; set; }

    public double? Elevation { get; set; }

    public virtual ICollection<Weather> Weather { get; set; } = new List<Weather>();

   
}